id: A69442B9D
title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily Practice
  Uniting the Short Lineages of Amitāyus and Hayagrīva'
type: translation
pechas:
- I8C1C6484
- IAC206064
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:34:24.707667
  last_modified_at: 2023-01-04 12:34:24.707674
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I8C1C6484/1ACF: 28C9
  IAC206064/C90D: 28C9
